---
# tasks file for apache2
- name: install web components
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - libapache2-mod-wsgi
  
- name: enable mod_wsgi in apache
  apache2_module: name=wsgi state=present
  notify: restart apache2

- name: delete default apache2 site
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: restart apache2   

- name: start apache2 service
  service: name=apache2 state=started enabled=yes  