---
- hosts: loadbalancer
  become: true
  gather_facts: false
  tasks:
    - name: Check nginx status
      command: service nginx status

    - name: Verify nginx is running on port 80
      wait_for: port=80 timeout=1  

- hosts: webserver
  become: true
  gather_facts: false
  tasks:
    - name: Check apache2 status
      command: service apache2 status

    - name: Verify Apache is running on port 80
      wait_for: port=80 timeout=1  

- hosts: database
  become: true
  tasks:
    - name: Check mysql status
      command: service mysql status            

    - name: Verify mysql is running on port 3306
      wait_for: host={{ ansible_eth0.ipv4.address }} port=3306 timeout=1

- hosts: control
  gather_facts: false
  tasks:
    - name: verify end-to-end response
      uri: url="http://{{ item }}" return_content=yes
      with_items: lb01
      register: lb_index

    - fail: msg="index failed to return content"
      when: "'Hello, from sunny' not in item.content"
      with_items: "{{ lb_index.results }}"

    - name: verify end-to-end db connection
      uri: url=http://{{ item }}/db return_content=yes
      with_items: lb01
      register: lb_db

    - fail: msg="db failed to return data"
      when: "'Database Connected from' not in item.content"
      with_items: "{{ lb_db.results }}"  

- hosts: loadbalancer
  gather_facts: false
  tasks:
    - name: verify end-to-end response
      uri: url=http://{{ item }} return_content=yes
      with_items: 
        - app01
        - app02
      register: app_index

    - fail: msg="App index failed to return content"
      when: "'Hello, from sunny {{ item.item }}' not in item.content"
      with_items: "{{ app_index.results }}"           
  
    - name: verify end-to-end db connection
      uri: url=http://{{ item }}/db return_content=yes
      with_items:
        - app01
        - app02
      register: lb_db

    - fail: msg="db failed to return data"
      when: "'Database Connected from {{ item.item }}' not in item.content"
      with_items: "{{ lb_db.results }}"
            

 